# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('EMdirK1_rcpparma_hello_world', PACKAGE = 'EMdirK1')
}

rcpparma_outerproduct <- function(x) {
    .Call('EMdirK1_rcpparma_outerproduct', PACKAGE = 'EMdirK1', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('EMdirK1_rcpparma_innerproduct', PACKAGE = 'EMdirK1', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('EMdirK1_rcpparma_bothproducts', PACKAGE = 'EMdirK1', x)
}

rowsum_Mat <- function(M) {
    .Call('EMdirK1_rowsum_Mat', PACKAGE = 'EMdirK1', M)
}

colsum_Mat <- function(M) {
    .Call('EMdirK1_colsum_Mat', PACKAGE = 'EMdirK1', M)
}

epan <- function(input) {
    .Call('EMdirK1_epan', PACKAGE = 'EMdirK1', input)
}

grad_EM_dir_K1_oe <- function(theta_u, network, N, K, T_data) {
    .Call('EMdirK1_grad_EM_dir_K1_oe', PACKAGE = 'EMdirK1', theta_u, network, N, K, T_data)
}

grad_EM_dir_K1_re <- function(theta_u, network, N, K, T_data) {
    .Call('EMdirK1_grad_EM_dir_K1_re', PACKAGE = 'EMdirK1', theta_u, network, N, K, T_data)
}

hess_EM_dir_K1_oe <- function(theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMdirK1_hess_EM_dir_K1_oe', PACKAGE = 'EMdirK1', theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

hess_EM_dir_K1_re <- function(theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMdirK1_hess_EM_dir_K1_re', PACKAGE = 'EMdirK1', theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

hess_EM_dir_K1_oe_re <- function(theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMdirK1_hess_EM_dir_K1_oe_re', PACKAGE = 'EMdirK1', theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

ELBO_conv_EM_dir_K1 <- function(theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMdirK1_ELBO_conv_EM_dir_K1', PACKAGE = 'EMdirK1', theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

grad_ELBO_K1_CV <- function(theta_u, gamma, network, N, K, T_data, test_node_set_len) {
    .Call('EMdirK1_grad_ELBO_K1_CV', PACKAGE = 'EMdirK1', theta_u, gamma, network, N, K, T_data, test_node_set_len)
}

hess_ELBO_K1_CV <- function(theta_u, gamma, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len) {
    .Call('EMdirK1_hess_ELBO_K1_CV', PACKAGE = 'EMdirK1', theta_u, gamma, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len)
}

ELBO_conv_K1_CV <- function(gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len) {
    .Call('EMdirK1_ELBO_conv_K1_CV', PACKAGE = 'EMdirK1', gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len)
}

