# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('EMundirK1Stab_rowsum_Mat', PACKAGE = 'EMundirK1Stab', M)
}

colsum_Mat <- function(M) {
    .Call('EMundirK1Stab_colsum_Mat', PACKAGE = 'EMundirK1Stab', M)
}

epan <- function(input) {
    .Call('EMundirK1Stab_epan', PACKAGE = 'EMundirK1Stab', input)
}

grad_EM_undir_K1_Stab <- function(theta_u, network, N, K, T_grid) {
    .Call('EMundirK1Stab_grad_EM_undir_K1_Stab', PACKAGE = 'EMundirK1Stab', theta_u, network, N, K, T_grid)
}

hess_EM_undir_K1_Stab <- function(theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMundirK1Stab_hess_EM_undir_K1_Stab', PACKAGE = 'EMundirK1Stab', theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

ELBO_conv_EM_undir_K1_Stab <- function(theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMundirK1Stab_ELBO_conv_EM_undir_K1_Stab', PACKAGE = 'EMundirK1Stab', theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

grad_ELBO_K1_CV <- function(theta_u, gamma, network, N, K, T_data, test_node_set_len) {
    .Call('EMundirK1Stab_grad_ELBO_K1_CV', PACKAGE = 'EMundirK1Stab', theta_u, gamma, network, N, K, T_data, test_node_set_len)
}

hess_ELBO_K1_CV <- function(theta_u, gamma, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len) {
    .Call('EMundirK1Stab_hess_ELBO_K1_CV', PACKAGE = 'EMundirK1Stab', theta_u, gamma, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len)
}

ELBO_conv_K1_CV <- function(gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len) {
    .Call('EMundirK1Stab_ELBO_conv_K1_CV', PACKAGE = 'EMundirK1Stab', gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len)
}

