# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('scEMundir_rowsum_Mat', PACKAGE = 'scEMundir', M)
}

colsum_Mat <- function(M) {
    .Call('scEMundir_colsum_Mat', PACKAGE = 'scEMundir', M)
}

epan <- function(input) {
    .Call('scEMundir_epan', PACKAGE = 'scEMundir', input)
}

gamma_update_sc_undir <- function(gamma, pi, theta, network, N, K) {
    .Call('scEMundir_gamma_update_sc_undir', PACKAGE = 'scEMundir', gamma, pi, theta, network, N, K)
}

grad_sc_EM_undir <- function(theta, gamma, network, N, K) {
    .Call('scEMundir_grad_sc_EM_undir', PACKAGE = 'scEMundir', theta, gamma, network, N, K)
}

hess_sc_EM_undir <- function(theta, gamma, N, K) {
    .Call('scEMundir_hess_sc_EM_undir', PACKAGE = 'scEMundir', theta, gamma, N, K)
}

ELBO_conv_sc_EM_undir <- function(gamma, pi, theta, network, N, K) {
    .Call('scEMundir_ELBO_conv_sc_EM_undir', PACKAGE = 'scEMundir', gamma, pi, theta, network, N, K)
}

