# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('EMundirStab_rowsum_Mat', PACKAGE = 'EMundirStab', M)
}

colsum_Mat <- function(M) {
    .Call('EMundirStab_colsum_Mat', PACKAGE = 'EMundirStab', M)
}

epan <- function(input) {
    .Call('EMundirStab_epan', PACKAGE = 'EMundirStab', input)
}

gamma_update_undir_Stab <- function(gamma, pi, theta, network, N, K, T_grid, grid_ids) {
    .Call('EMundirStab_gamma_update_undir_Stab', PACKAGE = 'EMundirStab', gamma, pi, theta, network, N, K, T_grid, grid_ids)
}

grad_EM_undir_Stab <- function(theta_u, gamma, network, N, K, nonzero_ids, nonzero_ids_len) {
    .Call('EMundirStab_grad_EM_undir_Stab', PACKAGE = 'EMundirStab', theta_u, gamma, network, N, K, nonzero_ids, nonzero_ids_len)
}

hess_EM_undir_Stab <- function(theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMundirStab_hess_EM_undir_Stab', PACKAGE = 'EMundirStab', theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

ELBO_conv_EM_undir_Stab <- function(gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMundirStab_ELBO_conv_EM_undir_Stab', PACKAGE = 'EMundirStab', gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

gamma_update_undir_CV <- function(gamma, pi, theta, network, N, K, T_grid, grid_ids, test_node_set_len) {
    .Call('EMundirStab_gamma_update_undir_CV', PACKAGE = 'EMundirStab', gamma, pi, theta, network, N, K, T_grid, grid_ids, test_node_set_len)
}

grad_EM_undir_CV <- function(theta_u, gamma, network, N, K, nonzero_ids, nonzero_ids_len, test_node_set_len) {
    .Call('EMundirStab_grad_EM_undir_CV', PACKAGE = 'EMundirStab', theta_u, gamma, network, N, K, nonzero_ids, nonzero_ids_len, test_node_set_len)
}

hess_EM_undir_CV <- function(theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len) {
    .Call('EMundirStab_hess_EM_undir_CV', PACKAGE = 'EMundirStab', theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len)
}

ELBO_conv_EM_undir_CV <- function(gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len) {
    .Call('EMundirStab_ELBO_conv_EM_undir_CV', PACKAGE = 'EMundirStab', gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len)
}

