# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('SEMdir_rowsum_Mat', PACKAGE = 'SEMdir', M)
}

colsum_Mat <- function(M) {
    .Call('SEMdir_colsum_Mat', PACKAGE = 'SEMdir', M)
}

epan <- function(input) {
    .Call('SEMdir_epan', PACKAGE = 'SEMdir', input)
}

gamma_update_dir <- function(gamma, pi, theta, network, N, K, T_grid, grid_ids) {
    .Call('SEMdir_gamma_update_dir', PACKAGE = 'SEMdir', gamma, pi, theta, network, N, K, T_grid, grid_ids)
}

grad_SEM_dir_oe <- function(theta_u, network, N, K, nonzero_ids, nonzero_ids_len, cluster_ids) {
    .Call('SEMdir_grad_SEM_dir_oe', PACKAGE = 'SEMdir', theta_u, network, N, K, nonzero_ids, nonzero_ids_len, cluster_ids)
}

grad_SEM_dir_re <- function(theta_u, network, N, K, nonzero_ids, nonzero_ids_len, cluster_ids) {
    .Call('SEMdir_grad_SEM_dir_re', PACKAGE = 'SEMdir', theta_u, network, N, K, nonzero_ids, nonzero_ids_len, cluster_ids)
}

hess_SEM_dir_oe <- function(theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, cluster_ids) {
    .Call('SEMdir_hess_SEM_dir_oe', PACKAGE = 'SEMdir', theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, cluster_ids)
}

hess_SEM_dir_re <- function(theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, cluster_ids) {
    .Call('SEMdir_hess_SEM_dir_re', PACKAGE = 'SEMdir', theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, cluster_ids)
}

hess_SEM_dir_oe_re <- function(theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, cluster_ids) {
    .Call('SEMdir_hess_SEM_dir_oe_re', PACKAGE = 'SEMdir', theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, cluster_ids)
}

ELBO_conv_SEM_dir <- function(gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, cluster_ids) {
    .Call('SEMdir_ELBO_conv_SEM_dir', PACKAGE = 'SEMdir', gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, cluster_ids)
}

VK_dir_oe <- function(theta, network, N, K, T_data, cluster_ids) {
    .Call('SEMdir_VK_dir_oe', PACKAGE = 'SEMdir', theta, network, N, K, T_data, cluster_ids)
}

VK_dir_re <- function(theta, network, N, K, T_data, cluster_ids) {
    .Call('SEMdir_VK_dir_re', PACKAGE = 'SEMdir', theta, network, N, K, T_data, cluster_ids)
}

HK_dir_oe <- function(theta, N, K, T_data, cluster_ids) {
    .Call('SEMdir_HK_dir_oe', PACKAGE = 'SEMdir', theta, N, K, T_data, cluster_ids)
}

HK_dir_re <- function(theta, N, K, T_data, cluster_ids) {
    .Call('SEMdir_HK_dir_re', PACKAGE = 'SEMdir', theta, N, K, T_data, cluster_ids)
}

HK_dir_oe_re <- function(theta, N, K, T_data, cluster_ids) {
    .Call('SEMdir_HK_dir_oe_re', PACKAGE = 'SEMdir', theta, N, K, T_data, cluster_ids)
}

