# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('EMundirK1_rowsum_Mat', PACKAGE = 'EMundirK1', M)
}

colsum_Mat <- function(M) {
    .Call('EMundirK1_colsum_Mat', PACKAGE = 'EMundirK1', M)
}

epan <- function(input) {
    .Call('EMundirK1_epan', PACKAGE = 'EMundirK1', input)
}

grad_EM_undir_K1 <- function(theta_u, network, N, K, T_data) {
    .Call('EMundirK1_grad_EM_undir_K1', PACKAGE = 'EMundirK1', theta_u, network, N, K, T_data)
}

hess_EM_undir_K1 <- function(theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMundirK1_hess_EM_undir_K1', PACKAGE = 'EMundirK1', theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

ELBO_conv_EM_undir_K1 <- function(theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMundirK1_ELBO_conv_EM_undir_K1', PACKAGE = 'EMundirK1', theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

grad_ELBO_K1_CV <- function(theta_u, gamma, network, N, K, T_data, test_node_set_len) {
    .Call('EMundirK1_grad_ELBO_K1_CV', PACKAGE = 'EMundirK1', theta_u, gamma, network, N, K, T_data, test_node_set_len)
}

hess_ELBO_K1_CV <- function(theta_u, gamma, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len) {
    .Call('EMundirK1_hess_ELBO_K1_CV', PACKAGE = 'EMundirK1', theta_u, gamma, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len)
}

ELBO_conv_K1_CV <- function(gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len) {
    .Call('EMundirK1_ELBO_conv_K1_CV', PACKAGE = 'EMundirK1', gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len)
}

