# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('scSEMundir_rowsum_Mat', PACKAGE = 'scSEMundir', M)
}

colsum_Mat <- function(M) {
    .Call('scSEMundir_colsum_Mat', PACKAGE = 'scSEMundir', M)
}

epan <- function(input) {
    .Call('scSEMundir_epan', PACKAGE = 'scSEMundir', input)
}

gamma_update_sc_undir <- function(gamma, pi, theta, network, N, K) {
    .Call('scSEMundir_gamma_update_sc_undir', PACKAGE = 'scSEMundir', gamma, pi, theta, network, N, K)
}

grad_sc_SEM_undir <- function(theta, network, N, K, cluster_ids) {
    .Call('scSEMundir_grad_sc_SEM_undir', PACKAGE = 'scSEMundir', theta, network, N, K, cluster_ids)
}

hess_sc_SEM_undir <- function(theta, N, K, cluster_ids) {
    .Call('scSEMundir_hess_sc_SEM_undir', PACKAGE = 'scSEMundir', theta, N, K, cluster_ids)
}

ELBO_conv_sc_SEM_undir <- function(gamma, pi, theta, network, N, K, cluster_ids) {
    .Call('scSEMundir_ELBO_conv_sc_SEM_undir', PACKAGE = 'scSEMundir', gamma, pi, theta, network, N, K, cluster_ids)
}

