# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('EMdir_rowsum_Mat', PACKAGE = 'EMdir', M)
}

colsum_Mat <- function(M) {
    .Call('EMdir_colsum_Mat', PACKAGE = 'EMdir', M)
}

epan <- function(input) {
    .Call('EMdir_epan', PACKAGE = 'EMdir', input)
}

gamma_update_dir <- function(gamma, pi, theta, network, N, K, T_grid, grid_ids) {
    .Call('EMdir_gamma_update_dir', PACKAGE = 'EMdir', gamma, pi, theta, network, N, K, T_grid, grid_ids)
}

grad_EM_dir_oe <- function(theta_u, gamma, network, N, K, nonzero_ids, nonzero_ids_len) {
    .Call('EMdir_grad_EM_dir_oe', PACKAGE = 'EMdir', theta_u, gamma, network, N, K, nonzero_ids, nonzero_ids_len)
}

grad_EM_dir_re <- function(theta_u, gamma, network, N, K, nonzero_ids, nonzero_ids_len) {
    .Call('EMdir_grad_EM_dir_re', PACKAGE = 'EMdir', theta_u, gamma, network, N, K, nonzero_ids, nonzero_ids_len)
}

hess_EM_dir_oe <- function(theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMdir_hess_EM_dir_oe', PACKAGE = 'EMdir', theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

hess_EM_dir_re <- function(theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMdir_hess_EM_dir_re', PACKAGE = 'EMdir', theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

hess_EM_dir_oe_re <- function(theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMdir_hess_EM_dir_oe_re', PACKAGE = 'EMdir', theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

ELBO_conv_EM_dir <- function(gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index) {
    .Call('EMdir_ELBO_conv_EM_dir', PACKAGE = 'EMdir', gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index)
}

VK_dir_oe <- function(theta, network, N, K, T_data, cluster_ids) {
    .Call('EMdir_VK_dir_oe', PACKAGE = 'EMdir', theta, network, N, K, T_data, cluster_ids)
}

VK_dir_re <- function(theta, network, N, K, T_data, cluster_ids) {
    .Call('EMdir_VK_dir_re', PACKAGE = 'EMdir', theta, network, N, K, T_data, cluster_ids)
}

HK_dir_oe <- function(theta, N, K, T_data, cluster_ids) {
    .Call('EMdir_HK_dir_oe', PACKAGE = 'EMdir', theta, N, K, T_data, cluster_ids)
}

HK_dir_re <- function(theta, N, K, T_data, cluster_ids) {
    .Call('EMdir_HK_dir_re', PACKAGE = 'EMdir', theta, N, K, T_data, cluster_ids)
}

HK_dir_oe_re <- function(theta, N, K, T_data, cluster_ids) {
    .Call('EMdir_HK_dir_oe_re', PACKAGE = 'EMdir', theta, N, K, T_data, cluster_ids)
}

gamma_update_dir_CV <- function(gamma, pi, theta, network, N, K, T_grid, grid_ids, test_node_set_len) {
    .Call('EMdir_gamma_update_dir_CV', PACKAGE = 'EMdir', gamma, pi, theta, network, N, K, T_grid, grid_ids, test_node_set_len)
}

grad_EM_dir_oe_CV <- function(theta_u, gamma, network, N, K, nonzero_ids, nonzero_ids_len, test_node_set_len) {
    .Call('EMdir_grad_EM_dir_oe_CV', PACKAGE = 'EMdir', theta_u, gamma, network, N, K, nonzero_ids, nonzero_ids_len, test_node_set_len)
}

grad_EM_dir_re_CV <- function(theta_u, gamma, network, N, K, nonzero_ids, nonzero_ids_len, test_node_set_len) {
    .Call('EMdir_grad_EM_dir_re_CV', PACKAGE = 'EMdir', theta_u, gamma, network, N, K, nonzero_ids, nonzero_ids_len, test_node_set_len)
}

hess_EM_dir_oe_CV <- function(theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len) {
    .Call('EMdir_hess_EM_dir_oe_CV', PACKAGE = 'EMdir', theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len)
}

hess_EM_dir_re_CV <- function(theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len) {
    .Call('EMdir_hess_EM_dir_re_CV', PACKAGE = 'EMdir', theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len)
}

hess_EM_dir_oe_re_CV <- function(theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len) {
    .Call('EMdir_hess_EM_dir_oe_re_CV', PACKAGE = 'EMdir', theta_u, gamma, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len)
}

ELBO_conv_EM_dir_CV <- function(gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len) {
    .Call('EMdir_ELBO_conv_EM_dir_CV', PACKAGE = 'EMdir', gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, test_node_set_len)
}

