# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('SEMundir_rowsum_Mat', PACKAGE = 'SEMundir', M)
}

colsum_Mat <- function(M) {
    .Call('SEMundir_colsum_Mat', PACKAGE = 'SEMundir', M)
}

epan <- function(input) {
    .Call('SEMundir_epan', PACKAGE = 'SEMundir', input)
}

gamma_update_undir <- function(gamma, pi, theta, network, N, K, T_grid, grid_ids) {
    .Call('SEMundir_gamma_update_undir', PACKAGE = 'SEMundir', gamma, pi, theta, network, N, K, T_grid, grid_ids)
}

grad_SEM_undir <- function(theta_u, network, N, K, nonzero_ids, nonzero_ids_len, cluster_ids) {
    .Call('SEMundir_grad_SEM_undir', PACKAGE = 'SEMundir', theta_u, network, N, K, nonzero_ids, nonzero_ids_len, cluster_ids)
}

hess_SEM_undir <- function(theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, cluster_ids) {
    .Call('SEMundir_hess_SEM_undir', PACKAGE = 'SEMundir', theta_u, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, cluster_ids)
}

ELBO_conv_SEM_undir <- function(gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, cluster_ids) {
    .Call('SEMundir_ELBO_conv_SEM_undir', PACKAGE = 'SEMundir', gamma, pi, theta_u, network, N, K, T_data, bandwidth, data_ids, grid_ids, grid_id_index, cluster_ids)
}

